- name: ensure nginx is at the latest version
  apt: name=nginx state=latest
  become: yes
  when: ansible_facts['distribution']=="Ubuntu"
       
- name: ensure nginx is at the latest version
  yum: name=nginx state=latest
  become: yes
  when: ansible_facts['distribution']=="RedHat"
